---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.6
    driver:
      box: local-chef-development
      box_url: https://s3.amazonaws.com/nathen-chef-lab/uscis.box

suites:
  - name: default
    run_list:
      - recipe[apache::default]
    attributes:
